### PR TITLE
Add system diagram.

### PR DESCRIPTION
**Pull request by dhananjay92**
I am working on awfy for Mozilla Servo (Issue [#5810](https://github.com/servo/servo/issues/5810)). I was trying to understand awfy's codebase and made this diagram. 
Sending in this pull because I think, it will be helpful documentation. Also in this pull, I can get my understanding of this codebase checked from you. :wink: 
Please let me know if I misunderstood something about awfy.

### CODE REVIEW

**Comment by h4writer** [comment]
That would definitely be helpful. Thanks!

Some questions:
* Can you also provide the ?svg? source of the image. Making it easier lateron to adjust something in the graph?
* Can you rename "UPDATE.php" into "Collector (website/UPDATE.php)"
* Can you rename "update.py" into "Processor (server/update.py)"

**Comment by dhananjay92** [comment]
Yup, done. Provided the SVG as well as updated the names.
We still have to use png image in README, because github doesn't render SVG images in README! See [Issue #316](https://github.com/isaacs/github/issues/316) for more details.

**Comment by dhananjay92** [comment]
Also added the link to Google Draw. Anyone can now create their own copy of it and edit it.

**Comment by h4writer** [comment]
Thanks for the help!

**Pull request merged**
